name: merge
on: 
   push:
   workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: |
          export repo=amitstudydude
          echo ${{ github.repository }}
          echo ${{ github.event.repository.name }}
          git clone https://github.com/amitstudydude/$repo.git
          mv "$repo"/* . 
          rm -rf "$repo"
          export token=${{ secrets.GITHUB_TOKEN }} && export ref=${GITHUB_REF:11} && export repo=$GITHUB_REPOSITORY          
          git config --global user.name 'amitstudydude'         
          git config --global user.email 'amitstudydude@users.noreply.github.com'         
          #git remote set-url origin https://x-access-token:$token@github.com/$repo          
          #git checkout "$ref"      
          git pull     
          git add -A          
          git commit -am "Automated report"         
          git push origin 
    
