name: merge
on: 
   push:
   workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: |
          export repo=amitstudydude
          git config --global user.name 'jha-oajka'
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          git pull --allow-unrelated
          git remote add upstream https://github.com/amitstudydude/$repo.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          
