name: merge
on: 
   push:
   workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: |
          export repo=amitstudydude
          git clone https://github.com/amitstudydude/$repo.git
          mv "$repo"/* . 
          rm -rf "$repo"
          export token=${{ secrets.GITHUB_TOKEN }} && export ref=${GITHUB_REF:11} && export repo=$GITHUB_REPOSITORY          
          git config --global user.name 'amitstudydude'         
          git config --global user.email 'amitstudydude@users.noreply.github.com'         
          git remote set-url origin https://x-access-token:$token@github.com/$repo          
          git checkout "$ref"          
          git add -A          
          git commit -am "Automated report"         
          git push origin main

          export repo=amitstudydude
          git config --global user.name 'jha-oajka'
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          git pull --unshallow  
          git remote add upstream https://github.com/amitstudydude/$repo.git
          git fetch upstream   
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
